### ISSUE TITLE
Can you make a video tutorial about macroMyKBD?

### ISSUE THREAD

**Issue by PotatoJet** [lal12/macroMyKBD#1]
I think it's difficult for many people to understand macroMyKBD,I really hope that you can make a video tutorial on Youtube,thank you very much.

**Comment by lal12** [comment]
Actually started to do that. However I had some troubles with screen capturing in my VM so I didn't try it again, yet.

**Comment by PotatoJet** [comment]
> Actually started to do that. However I had some troubles with screen capturing in my VM so I didn't try it again, yet.

All right,waiting for your good news.

**Comment by KGT1** [comment]
I did one:
https://youtu.be/k5ltJ_6T3qI

**Comment by PotatoJet** [comment]
> 我做了一个：[https](https://youtu.be/k5ltJ_6T3qI) :
> [//youtu.be/k5ltJ_6T3qI](https://youtu.be/k5ltJ_6T3qI)

Thank you very much.It works!
But how to integrate all key's ahk script into one AHK script?(I don't want A.ahk B.ahk C.ahk....)
Thanks again.
