### ISSUE TITLE
How can i restart macroMyKBD every time i edit actions.yml?

### ISSUE THREAD

**Issue by kkarakk** [lal12/macroMyKBD#11]
I've just started using this tool and the only minor annoyance i have is having to manually close the cmd window and restart the utility every time i edit actions.yml. Gets quite tedious especially as i fine tune my workflow. 

Is there any way to have this hot reload every time actions.yml is edited?

**Comment by lal12** [comment]
No currently is it not possible. But I am currently working on a version with GUI, where you won't have to edit the config manually anyway. I hope I can release it sometime next week.

**Comment by lal12** [comment]
Well it just came to my mind that there are programs which can watch a file and automatically restart a process on change. E.G. there are PowerShell scripts for that or there is webproc. But nothing totally simple or out of the box that I am aware of.
