### ISSUE TITLE
Media Keys and other Keys outside of the 0x07**** usb keycode block cannot be assigned 

### ISSUE THREAD

**Issue by KGT1** [lal12/macroMyKBD#3]
I get that it is more readable in the output and in the actions.yml like this, however many keyboards have keys like media keys or others which cannot be assigned like this.

**Comment by lal12** [comment]
Could you give some more elaborate info on that? I am not quite sure what's the problem there. Also can't really test this since I have no keyboard with media keys (or more honestly don't know where I put it ^^).

**Comment by KGT1** [comment]
if you look in server/hid_ps2.ts you can see that MMKBD only uses the usb keycodes with 07 in hex at the beginning than they are converted to decimal and used as keycodes like that.
Example:
```
const codetable = [
    //USB       XKB     Win     Mac     Desc1                   Desc2           (Desc3)
    [0x070045, 0x0060, 0x0058, 0x006f, "F12",					"F12" ],
    [ 0x0c00cd, 0x0000, 0xe022, 0xffff, "MediaPlayPause",		"MEDIA_PLAY_PAUSE" ]

]
```
here you convert just the 0x070045 to a 69. Why not just leave it 0x070045?
you commented this with `// assign standard keys (in block 07)` that makes every button without 0x07**** deprecate, even tho there are many buttons that dont have 07 at the front.

**Comment by KGT1** [comment]
Of course this would be a bigger change since MMKBD uses these Keycodes everywhere


>   - cmd: 'start cmd.exe'
>     events: 
>       **- keys: [227, 6]**
>         on: 'down'
>         only: true
>         device: 1

I suspect you used numbers instead of the hex values for the sake of simplicity,
correct me if I am wrong.

**Comment by lal12** [comment]
Ok thanks. I looked into it, I think I did it because the previous underlying lib I used to send the inputs didn't supported other codes (>0xFF). However later during development I switched to [my own implementation](https://github.com/lal12/node-sendinput), so I probably can change  that.

**Comment by KGT1** [comment]
i have looked into it and it seems that at least with my keyboard i can only get the normal 0x07xxxx scan codes, with the library libusb, so I dont really know how to continue on this.
