### ISSUE TITLE
macroMyKBD work with AutoHotKey?

### ISSUE THREAD

**Issue by PotatoJet** [lal12/macroMyKBD#8]
@KGT1  @lal12  #1 
Thank you for your video tutorial.It works!
But how to integrate all key's AHK script into one AHK script?
I don't want A.ahk B.ahk C.ahk...
I want just one script like this↓↓↓

```
A::msgbox, KGT1 is good man

B::msgbox, lal12 is genius

C::msgbox, I'm superman
```

I really appreciate it.
If there's no way, it's OK.

**Comment by lal12** [comment]
Yes you can. How depends a little bit on what you want to do, but the easiest way to just look for a **single** key event is this:

```ahk
EnvGet, evtKeyCodes, EVENT_KEYS

switch evtKeyCodes
{
case "4":
    MsgBox, You have pressed A
    return
case "5":
    MsgBox, You have pressed B
    return
case "6":
    MsgBox, You have pressed C
    return
default:
    MsgBox, A not handled keyCode "%evtKeyCodes%" was received
}

```
This can work for multiple keys too, but needs a bit more code in the AHK script.

Though I am not really familiar around AHK scripting, nor can I currently test this, so it might need a bit of tweaking.

A bit of explanation what it does:
`EnvGet, evtKeyCodes, EVENT_KEYS` reads a so called environment variable `EVENT_KEYS` which is passed from macroMyKBD and puts it into the local variable `evtKeyCodes`;

`switch evtKeyCodes` "look into the variable and jump to the matching `case` statement, if there is no matching `case` jump to `default` instead".

**Comment by PotatoJet** [comment]
Thank you for your reply.
I will have a try.
